### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by fangpenlin**

### CODE REVIEW

**Comment by diegoeche** [comment]
Cool! Way more readable. I find there's little test coverage by looking at the /spec folder.

Can you maybe add some integration tests?

Also the lambda part of the processing is a mistery. Can you dumb down the README a little bit?

**Comment by fangpenlin** [comment]
@diegoeche sure, will do

**Comment by fangpenlin** [comment]
@diegoeche I have integration test in place, and also added the lambda project in readme. can you review it again?

**Review by diegoeche — COMMENTED** [review]
Sorry I skipped it. Thanks so much for all the fixes.

**Pull request merged**
